# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
